[Unit]
Requires=nativecontainers-baseline-firewall.service nativecontainers-agent.service nativecontainers-network-authorization.service
After=nativecontainers-baseline-firewall.service nativecontainers-agent.service nativecontainers-network-authorization.service
BindsTo=nativecontainers-network-authorization.service
